# Generated by Django 6.0.6 on 2026-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirEnvio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
